[build-system]
requires = ["uv_build >= 0.9.5, <0.10.0"]
build-backend = "uv_build"

[project]
version = "2025.0.0"
name = "codspeed-example"
requires-python = ">= 3.13"
dependencies = [
    "pytest-codspeed>=4.2.0",
]
